version: "3.8"

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - minio_data:/data
    command: server --console-address ":9090" /data
    networks:
      - maldeals_network
  deals.db:
    image: postgres:latest
    container_name: deals.db
    environment:
      POSTGRES_USER: malDeals
      POSTGRES_PASSWORD: deals_password
      POSTGRES_DB: deals_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - maldeals_network
    volumes:
      - postgres:/var/lib/postgresql/data

 # pgadmin:     
  #  image: dpage/pgadmin4
   # container_name: pgadmin
    #environment:
     # PGADMIN_DEFAULT_EMAIL: emami@gmail.com
      #PGADMIN_DEFAULT_PASSWORD: password
    #ports:
     # - "5050:80"
    #volumes:
     # - pgadmin-data:/var/lib/pgadmin
    #restart: always
    #depends_on:
     # - deals.db
    #networks:
     # - maldeals_network

volumes:
  postgres:
  pgadmin-data:
  minio_data:

networks:
  maldeals_network: