version: "3"

services:
  deals.db:
    image: postgres:latest
    container_name: deals.db
    environment:
      POSTGRES_USER: malDeals
      POSTGRES_PASSWORD: deals_password
      POSTGRES_DB: deals_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - maldeals_network
    volumes:
      - postgres:/var/lib/postgresql/data  # Persistent storage für PostgreSQL

 # pgadmin:     
  #  image: dpage/pgadmin4
   # container_name: pgadmin
    #environment:
     # PGADMIN_DEFAULT_EMAIL: emami@gmail.com
      #PGADMIN_DEFAULT_PASSWORD: password
    #ports:
     # - "5050:80"
    #volumes:
     # - pgadmin-data:/var/lib/pgadmin
    #restart: always
    #depends_on:
     # - deals.db
    #networks:
     # - maldeals_network

volumes:
  postgres:
  pgadmin-data:

networks:
  maldeals_network: